services:
  - type: web
    name: maritime-weather-dashboard
    env: node
    plan: free
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: development
